services:
  redis:
    image: redis:7.4-alpine
    container_name: redis-${PROJECT_NAME}
    restart: always
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis_data:/data
    command: ['redis-server', '--save', '60', '1', '--loglevel', 'warning']

volumes:
  redis_data:
